import ProofNet.Artin
import ProofNet.Axler
import ProofNet.Cambridge-Tripos
import ProofNet.Dummit-Foote
import ProofNet.Herstein
import ProofNet.Ireland-Rosen
import ProofNet.Munkers
import ProofNet.Pough
import ProofNet.Putnam
import ProofNet.Rudin
import ProofNet.Shakarachi