import ProofNet.Artin
import ProofNet.Axler
import ProofNet.Cambridge_Tripos
import ProofNet.Dummit_Foote
import ProofNet.Herstein
import ProofNet.Ireland_Rosen
import ProofNet.Munkers
import ProofNet.Pough
import ProofNet.Putnam
import ProofNet.Rudin
import ProofNet.Shakarachi