import formal.Artin
import formal.Axler
import formal.Cambridge_Tripos
import formal.Dummit_Foote
import formal.Herstein
import formal.Ireland_Rosen
import formal.Munkers
import formal.Pough
import formal.Putnam
import formal.Rudin
import formal.Shakarachi